### ISSUE TITLE
tests failing

### ISSUE THREAD

**Issue by phanrahan** [leonardt/hwtypes#105]
Not sure what I need to do to fix this. `bit_vector.py` doesn't exist.

```
Traceback:
tests/test_adt.py:4: in <module>
    from hwtypes.modifiers import new
hwtypes/__init__.py:7: in <module>
    from .fp_vector import *
hwtypes/fp_vector.py:7: in <module>
    from .bit_vector import Bit, BitVector, SIntVector
E   ModuleNotFoundError: No module named 'hwtypes.bit_vector'
```

**Comment by rdaly525** [comment]
That is a strange error... Are you sure you are running from hwtypes:master?
Can you check if hwtypes/hwtypes/bit_vector.py is in your local repo?
Also have you tried a fresh environment?

**Comment by phanrahan** [comment]
I cloned it from scratch. Now it works. Not sure what happened.
