### ISSUE TITLE
Too eager of casting in SMTBit.ite

### ISSUE THREAD

**Issue by rdaly525** [leonardt/hwtypes#107]
I would expect the following to raise a type error. Is this expected behavior or a bug?

```
p = SMTBit()
t = SMTBit()
f = SMTBitVector[1]()
#This does not raise a type error
res = p.ite(t,f)
```

**Comment by cdonovick** [comment]
This basically is question about whether the following should work: `bit.ite(bv, 5)`
All of the other operators / methods currently will try to coerce there operands.  The fact the operand is a bit should not matter to this rule.

**Comment by cdonovick** [comment]
I am fine with removing coercion from the ITE.  I am not okay with special casing bit.

**Comment by cdonovick** [comment]
Actually I think I can block this specific behavior by first trying to cast to bit, before tying to cast to bv.
