### ISSUE TITLE
NameError bug with AttrSyntax

### ISSUE THREAD

**Issue by rdaly525** [leonardt/hwtypes#119]
The following test

```
from hwtypes.adt import Product

def test_bug():
    class A(Product):
        a=str

    class B(Product):
        A=A
```

Produces the error:

`NameError: name 'A' is not defined`

Weirdly, if you define the classes outside any function, it does not raise the error. Also the same error occurs with TaggedUnion

**Comment by cdonovick** [comment]
This is how python works.   Nothing to do with hwtypes.   https://docs.python.org/3/reference/executionmodel.html#resolution-of-names

> If a name binding operation occurs anywhere within a code block, all uses of the name within the block are treated as references to the current block. This can lead to errors when a name is used within a block before it is bound. This rule is subtle. Python lacks declarations and allows name binding operations to occur anywhere within a code block. The local variables of a code block can be determined by scanning the entire text of the block for name binding operations.
