### ISSUE TITLE
Make bitvector ABC

### ISSUE THREAD

**Issue by cdonovick** [leonardt/hwtypes#16]
We should create a BitVector ABC to aid abstraction of the BV types.

This ideally would provide mixin methods where appropriate, e.g. define  `bvnot` and `bvand` get `bvnand` for free.  

Crazy idea: I think we could get away with requiring only `__getitem__`, `concat`, and `bvnand`  for all of the `bv*` methods but that would lead to inefficient code so we probably don't want to encourage that.

We might want to add a make_constant method, this would make abstracting over Bit Vector types easier as their constructors are not guaranteed to be uniform (e.g. a smt_bitvector needs to bound to a solver and Bit is already bound to numbits https://github.com/phanrahan/peak/blob/mapper/peak/mapper/SMT_bit_vector.py)

```Python
def make_constant(self, value:int, num_bits:typing.Optional[int] = None) -> type(self):
  if num_bits is None:
    num_bits = self.num_bits
  #else:
  #  if a type with a bound size (e.g. Bit) construct a type of an appropriate size 
  return type(self)(value, num_bits)
```

**Comment by phanrahan** [comment]
These all seem like good ideas.

@cdonovick, any chance you could draft an abc class for bitvector so we can make all this more concrete?

**Comment by cdonovick** [comment]
@phanrahan okay will draft one

**Comment by cdonovick** [comment]
@phanrahan @leonardt 
https://github.com/cdonovick/bit_vector/blob/abc/bit_vector/bit_vector_abc.py
https://github.com/cdonovick/bit_vector/blob/abc/bit_vector/bit_vector.py

**Comment by leonardt** [comment]
Closed by https://github.com/leonardt/bit_vector/pull/17, let's open more specific issues as they arise.
