### ISSUE TITLE
`__int__` for Bit

### ISSUE THREAD

**Issue by leonardt** [leonardt/hwtypes#32]
@cdonovick did we intentionally decide not to include `__int__` for bit?  If not, I can add support, but wanted to double check.

I have the following code
```
    while sum(bool(x < 0) for x in inputs) < 3:
```

Originally I had `bool` as `int` (to convert to int for the sum). However, using `bool` is fine because `True + True == 2` in python.

**Comment by cdonovick** [comment]
There is no reason we can't have `__int__` on Bit.  The one thing to keep in mind is both `__bool__`  and `__int__` cannot be supported by SMT and magma I assume.
