### ISSUE TITLE
semantics for Bitvector concat is opposite of magma concat

### ISSUE THREAD

**Issue by rdaly525** [leonardt/hwtypes#45]
semantics for magma.concat is concat(lsbs,msbs) while hwtypes.BitVector.concat is concat(msbs,lsbs)

We should unify the semantics. I would prefer magma's version but at the end of the day, it does not matter.

**Comment by phanrahan** [comment]
We store bits such that the 0th (lsb) is indexed as 0. The magma concat would be consistent with the normal list concat. I suggest we change the implementation in hwtypes.

**Comment by cdonovick** [comment]
The hwtypes implementation is consistent with SMTLib which also has lsb 0 semantics.  I am fine with it either way though.
