### ISSUE TITLE
len of BitVector class

### ISSUE THREAD

**Issue by leonardt** [leonardt/hwtypes#47]
I tried writing this:
```python
>>> import hwtypes
>>> len(hwtypes.BitVector[32])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: object of type 'AbstractBitVectorMeta' has no len()
```

I found that I can write `hwtypes.BitVector[32].size` to get what I want, but should we consider adding support for `len`? Or is there an issue that I'm not aware of?

**Comment by cdonovick** [comment]
Adding `__len__` to `AbstractBitVectorMeta` should not be an issue.
