### ISSUE TITLE
SMT BitVector corner cases

### ISSUE THREAD

**Issue by leonardt** [leonardt/hwtypes#7]
If we want to match the SMT semantics, we should watch out for
```
x / 0 == -1
x % 0 == x
```

**Comment by phanrahan** [comment]
I believe
```
x // 0 == 1
x % 0 == x
```
The reason for specifying divide by 0 is that they want total functions (always well-defined).

This logic guarantees the following theorem holds:
```
(x // y) * y + (x % y) = x
```

This should be implemented in my PR.

**Comment by leonardt** [comment]
We've addressed the specific mentioned issues, we can open up new issues to track this if we run into them.
