### ISSUE TITLE
[feature-request] Product types defined the same way should be the same object.

### ISSUE THREAD

**Issue by rdaly525** [leonardt/hwtypes#76]
I Ideally would like the following to work.

```
A0 = Product.from_fields("A",{"a":int})
A1 = Product.from_fields("A",{"a":int})
assert A0 is A1

```
I do not think this would change any existing code and would be immensely helpful.

**Comment by cdonovick** [comment]
This would potentially break existing code (the bitfield stuff).

However I would be open to the following modification:
```
class A(Product):
   a = int

B = Product.from_fields('B', {'a' : int})

assert A == B
```
Basically make Identical products types equal.

**Comment by rdaly525** [comment]
That is fine.

This is mostly for user code on checking the type of Sum types.
