### ISSUE TITLE
Method to construct a default value on all ADT types and all BitVector Types

### ISSUE THREAD

**Issue by rdaly525** [leonardt/hwtypes#78]
This has come up in a few situations where I needed to construct a default value.

Specifically when I needed the structure of the adt type so that I could modify it, also default values when calling peak objects (peak.register) for example.

**Comment by cdonovick** [comment]
@rdaly525 is this still an issue? can you be more concrete?

**Comment by rdaly525** [comment]
I think this is unneeded now that we have assembled-adt. Closing
